# Generated by Django 6.0.2 on 2026-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGDBAdminEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'IGDB Search',
                'verbose_name_plural': 'IGDB Search',
                'managed': False,
            },
        ),
    ]
