# Generated by Django 6.0.2 on 2026-04-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='medium',
            field=models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], default='physical', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
