# Generated by Django 6.0.2 on 2026-04-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_game_condition_game_medium_game_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='game',
            name='medium',
        ),
        migrations.AddField(
            model_name='game',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
