# Generated by Django 6.0.2 on 2026-02-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_genre_platform_game_slug_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genre_textures/'),
        ),
        migrations.AddField(
            model_name='platform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='platform_textures/'),
        ),
    ]
