# Generated by Django 6.0.2 on 2026-02-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_game_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
