# Generated by Django 6.0.2 on 2026-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='storefront_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
