# Generated by Django 6.0.2 on 2026-04-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_game_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='manufacturer',
            field=models.CharField(default='PC', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='manufacturer_slug',
            field=models.SlugField(blank=True),
        ),
    ]
