# Generated by Django 6.0.2 on 2026-04-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_game_storefront_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='game_banners/'),
        ),
    ]
