# Generated by Django 6.0.2 on 2026-04-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_game_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
