# Generated by Django 6.0.2 on 2026-04-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_game_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_name', models.CharField(max_length=255, unique=True)),
                ('local_name', models.CharField(max_length=255)),
            ],
        ),
    ]
